name: dart_server
publish_to: none # not intended for publication to pub.dev

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  dotenv: ^4.0.1
  shelf: ^1.2.0
  shelf_router: ^1.0.0
  shelf_static: ^1.0.0
  supabase: ^0.3.6

dev_dependencies:
  http: ^0.13.0
  lints: ^2.0.0
  test: ^1.15.0
  test_process: ^2.0.0
